### Listar produtos
GET http://localhost:3000

### Requisição passando parametros na URL
GET http://localhost:3000/12345678910

### Cadastrar produto
POST http://localhost:3000
Content-Type: application/json

{
    "nome" : "Junior",
    "cpf"  : "12345678910",
    "horas" : "100",
    "valor" : "50",
    "mes" : "5",
    "ano" : "2023"
}
